# Generated by Django 4.1.2 on 2022-10-16 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preonboard', '0003_applicate_modify_date_job_opening_modify_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicate',
            name='content',
        ),
        migrations.AddField(
            model_name='applicate',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicate',
            name='job_opening',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='preonboard.job_opening'),
            preserve_default=False,
        ),
    ]
