# Generated by Django 4.1.2 on 2022-10-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preonboard', '0004_remove_applicate_content_applicate_applicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_opening',
            name='country',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_opening',
            name='location',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_opening',
            name='wanted',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
