# Generated by Django 4.1.2 on 2022-10-16 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preonboard', '0005_job_opening_country_job_opening_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_opening',
            name='country',
        ),
        migrations.RemoveField(
            model_name='job_opening',
            name='location',
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('country', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='job_opening',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preonboard.company'),
        ),
    ]
